config/routes.rb
Rails.application.routes.draw do

 
  devise_for :users
  root 'posts#index'
  get 'locale', to: 'locales#save_locale', as: :set_locale
  resources :posts do
    

    collection do
      get :published
      get :surprise
    end
  end
 
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    before_create :titleize_author

    after_create :notify_admin

    mount_uploader :picture, PictureUploader

    def notify_admin
       PostFetchJob.perform_later(self)
    end

    private
    def titleize_author
        self.author = self.author.to_s.titleize
    end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :set_locale

    def set_locale
    I18n.locale = session[:locale] || I18n.default_locale
    end

end

app/controllers/locales_controller.rb
class LocalesController < ApplicationController
    def save_locale
      session[:locale] = params[:locale]
      redirect_back fallback_location: root_path
    end
  end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]

  def index
    @posts = Post.page(params[:page]).per(3)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.save
    respond_to do |format|
      format.html do 
        flash[:notice] = "Dziękujemy za wpis"
        redirect_to posts_path
    end
    format.js {}
  end
  end


  def surprice
  end

  private 
  def post_params
    params.require(:post).permit(:author, :picture, :body)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/locales_helper.rb
module LocalesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GuestBook</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%# <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="page-header">

        <%if flash[:notice]%>
          <div class="alert alert-success">
            <%= flash[:notice]%>
          </div>
        <%end%>
        <h1>Księga gości</h1>
      </div>
      <%= yield %>

      <% if user_signed_in? %>
        <p><%= link_to "Wyloguj się", destroy_user_session_path, method: :delete %>
        </p>
      <% end %>
    </div>

  </body>
</html>

app/views/posts/create.js.erb
$("#form-container").hide(500, function() {
  $("#form-container").html("<p class=\"alert alert-success\">Dziękujemy za wpis!</p>");
  $("#form-container").show();
});

app/views/posts/index.html.erb
<div class="dropdown">
  <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
    <%= t "index.select_language", language: I18n.locale %>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
    <li><%= link_to "PL", set_locale_path(locale: "pl")%></li>
    <li><%= link_to "EN", set_locale_path(locale: "en")%></li>

  </ul>
</div>

<pre>
<%= I18n.localize Time.now, format: :short%>
<%= l Date.today, format: :short %>
<%= number_with_delimiter(1123131232.1231231231) %>
<%= number_to_currency 1254.4444444 %>
<%= distance_of_time_in_words(rand(10_000).seconds) %>
</pre>

<% if user_signed_in? %>
  <p class="lead">
    <%= t "index.hello"%>
    <%= link_to "Dodaj własny wpis już teraz.", new_post_path %>
  </p>
<% else %>
  <p class="lead">
    <%= t "index.hello"%>
    Musisz się zalogować, aby dodać wpis.
    <%= link_to "Zaloguj się", new_user_session_path %>
  </p>
<% end %>
<div id="content-placeholder">
  <%= link_to "Niespodzianka", surprise_posts_path, class: "btn btn-info", remote: true%>
</div>

<% @posts.each do |post| %>
  <div class="row">
    <div class="col-md-4">
      <%= image_tag post.picture.url(:thumb) %>
    </div>
    <div class="col-md-8">
      <blockquote>
        <p><%= post.body%></p>
        <footer><cite><%= post.author%></cite></footer>
      </blockquote>
    </div>
  </div>

<% end %>

<%= paginate @posts %>

app/views/posts/new.html.erb
<div id="form-container">
  <h2>Dodawanie nowego wpisu</h2>

  <%= form_for @post, remote: true do |f| %>
    <div class="form-group">
      <%= f.label :author, "Autor"%>
      <%= f.text_field :author, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :picture, "Obrazek"%>
      <%= f.file_field :picture, class: "form-control" %>
    </div>
    <div class="form-group">
      <%= f.label :body, "Treść"%>
      <%= f.text_area :body, class: "form-control" %>
    </div>

    <%= f.submit "Dodaj wpis", class: "btn btn-default" %>
  <%end%>
</div>

<%# <div> %>
<%# <h2>Formularz simple_for</h2> %>

<%# <%= simple_form_for @post do |f| %> 
<%# <%= f.input :author, label: "Autor", hint: "Podaj nick" %>
<%# <%= f.input :body %>
<%# <%= f.submit class: "btn btn-default" %>

<%# <%end%>

<%# </div> %>

app/views/posts/surprise.js.erb
<%# alert("JS zamiast html <%=Time.now") %>

$("#content-placeholder").html("<p>TRR</p>")


<%# document.getElementById("content-placeholder").innerHTML = "<p>TRE</p>" %>